# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
# ref https://gist.github.com/azihsoyn/7f307e39e4a493c24235367e711e3725
version: 2
jobs:
  # If you are not using workflows, the jobs map must contain a job named build (default)
  build:
    working_directory: /go/src/github.com/so0k/aws-nat-router
    docker:
      - image: circleci/golang:q.10.0
    environment:
      - GOCACHE: "/tmp/go/cache"
      - DEP_VERSION: 0.4.1
    steps:
      - run: git config --global url.ssh://git@github.com/so0k.insteadOf https://github.com/so0k
      - checkout
      - restore_cache:
          key: gopkg-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
          paths:
              - /go/src/github.com/so0k/aws-nat-router/vendor
      - run:
          name: download-libraries
          command: |
            if [ ! -d /go/src/github.com/so0k/aws-nat-router/vendor ]; then
                curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o /go/bin/dep
                chmod +x /go/bin/dep
                /go/bin/dep ensure
            fi
      - save_cache:
          key: gopkg-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
          paths:
              - /go/src/github.com/so0k/aws-nat-router/vendor
      - restore_cache:
          keys:
              - build-cache-{{ .Branch }}-{{ .Environment.CIRCLE_PREVIOUS_BUILD_NUM }}
          paths:
              - /tmp/go/cache
      - run:
          name: test
          command: |
            mkdir -p $GOCACHE
            go build -v -o ./bin/aws-nat-router cmd/aws-nat-router/main.go 
            go test -p 6 -race ./cmd/aws-nat-router/...
      - save_cache:
          key: build-cache-{{ .Branch }}-{{ .Environment.CIRCLE_BUILD_NUM }}
          paths:
              - /tmp/go/cache
      - persist_to_workspace:
          root: ./bin
          paths:
            - aws-nat-router
      - store_artifacts:
          path: ./bin/aws-nat-router
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./bin
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(./bin/aws-nat-router --version | cut -d" " -f3)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./bin
workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:  # required since `publish-github-release` has tag filters AND requires `build`
            tags:
              only: /.*/ # run for all branches and all tags
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/ # only run for tags that match this regex
